### ISSUE TITLE
Rearrange pie chart ordering to make more sense

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#16]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2022-01-17 202127](https://user-images.githubusercontent.com/52340127/149742468-da240e7d-719e-4e58-aa80-2595531ec93e.png)
Currently the pie chart ordering makes little sense (good borders very bad and very good, bad borders very good).

**Describe the solution you'd like**
Rearrange the pie chart to very bad, bad, good, very good going anticlockwise.

**Comment by someretical** [comment]
The pie chart is organized so that the category with the MOST days is furthest right. In your example, the good and bad days both have an equal number.

```c++
        // Display pie chart slices from largest to smallest.
        auto sorted = std::vector<std::pair<td::Rating, int>>();
        for (int i = 1; i < 6; ++i)
            if (0 != rating_counts[i])
                sorted.push_back(std::pair(static_cast<td::Rating>(i), rating_counts[i]));

        std::sort(sorted.begin(), sorted.end(), [](auto const &a, auto const &b) { return a.second > b.second; });
```
Here is the code responsible for doing that. Note that `std::sort` is a stable sort.

Originally, I actually did implement it in the way you suggested since it was so easy.

**Comment by queze1** [comment]
I would personally prefer the way I suggested.

**Comment by someretical** [comment]
I will add a setting toggle for your version.
