### ISSUE TITLE
Add something to indicate the current date

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#6]
An mockup for what could be added to indicate the entry for the current date. 
![Screenshot 2021-11-19 193052](https://user-images.githubusercontent.com/52340127/142591277-905cc646-e5c3-4cfd-912f-c3ac53f8c5f5.png)

**Comment by someretical** [comment]
I agree that this is a good feature but it will be a pain to indicate. With the current system, a custom painter for the button will need to be added. This is something I have intentionally held off from doing (instead preferring to use stylesheets) since it is really complicated. 

EDIT:
This is also the reason why I implemented the 'Jump to today' button. 
Also I just wanted to ask how you would feel if I simply changed the color of the current date number to indicate it as today? 
The only issue I can think of is that each rating has its own background colour so it will be hard to find a contrasting colour for all 6 background colours. If you could help find a suitable colour, that would be really nice.

**Comment by queze1** [comment]
I will install the latest version today and check the new version.

> Also I just wanted to ask how you would feel if I simply changed the color of the current date number to indicate it as today?
I think that could be enough to show the current date, although I think that a circle around the date would look a bit better.

**Comment by someretical** [comment]
Just adding this comment so I don't forget.

When implementing the current day feature, consider if and when the app should update the indicator since the user may be using the app close to 12am.

**Comment by someretical** [comment]
As of the current commit (38da0254ba7fbfc7dc2892685caef5985d8ecd21), the current date is indicated by the italicized day number in the diary editor menu.
![image](https://user-images.githubusercontent.com/29365738/149659366-a5bced20-cb86-465a-84b6-c253aa571707.png)
For future reference, the buttons are repainted in the `paintEvent()` function so it should happen regularly enough.
